export enum Statuses {
  RECEIVED = 'RECEIVED',
  PAYMENT_PROCESSED = 'PAYMENT_PROCESSED',
  PACKING = 'PACKING',
  SHIPPED = 'SHIPPED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
}
